#******************************************************************************#
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: agissing <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2018/09/15 20:46:17 by agissing          #+#    #+#              #
#    Updated: 2018/09/15 22:19:41 by agissing         ###   ########.fr        #
#                                                                              #
#******************************************************************************#

.SILENT:

all:
	cc -Wall -Werror -Wextra srcs/basics.c			\
							srcs/ft_comp.c			\
							srcs/ft_dimensions.c	\
							srcs/ft_rush_x.c		\
							srcs/struct_builder.c	\
							srcs/main.c				\
							-o colle-2

fclean:
	rm -f colle-2

re: fclean all