#******************************************************************************#
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: agissing <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2018/09/15 20:46:17 by agissing          #+#    #+#              #
#    Updated: 2018/09/15 20:48:06 by agissing         ###   ########.fr        #
#                                                                              #
#******************************************************************************#

.SILENT:

all:
	cc -Wall -Werror -Wextra basics.c ft_comp.c ft_dimensions.c ft_rush0X.c struct_builder.c test.c -o colle-2

fclean:
	rm -f colle-2

re: fclean all